// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Customupload: typeof import('./src/components/Customupload.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Fileupload: typeof import('./src/components/Fileupload.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
